// API_BASE is empty — all requests go to /api/proxy/... on the same Next.js
// server, which forwards them to the Flask API with the user's Bearer token.
// The token is never exposed to the browser bundle.
export const API_BASE = "";

// The user's unique token is stored in localStorage (set by the dashboard on
// first load from the URL hash, or manually via the options page).
// It is the same token auto-generated by the extension in background.js.
function getToken(): string {
  if (typeof window === "undefined") return "";
  return localStorage.getItem("ng_token") ?? "";
}

export function authHeaders(): HeadersInit {
  const token = getToken();
  return token
    ? { "Content-Type": "application/json", Authorization: `Bearer ${token}` }
    : { "Content-Type": "application/json" };
}

export async function apiFetch<T>(
  path: string,
  opts: RequestInit = {}
): Promise<T> {
  const res = await fetch(`${API_BASE}${path}`, {
    ...opts,
    headers: {
      ...authHeaders(),
      ...(opts.headers ?? {}),
    },
  });
  if (!res.ok) throw new Error(`HTTP ${res.status} — ${path}`);
  return res.json() as Promise<T>;
}
